# Generated by Django 3.2.10 on 2021-12-28 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='peoples.peoples')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='peoples.peoples')),
            ],
        ),
    ]
