# Generated by Django 3.2.10 on 2021-12-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='peoples.peoples'),
        ),
        migrations.AlterField(
            model_name='deals',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='peoples.peoples'),
        ),
    ]
